CREATE TABLE users (
    id CHAR(36)  PRIMARY KEY NOT NULL DEFAULT (UUID()),
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category INT NOT NULL DEFAULT 0,
    dob DATE,
    bio LONGTEXT,
    avatar VARCHAR(255)
);